README.md

Full Stack Readme update

---

react/06.react_map.md

map in react

---

react/12.react_classbased_components.md
react/13.react_functional_componets.md
react/14.react_useContext.md
react/15.react_useMemo_and_useCallback.md

added,
useMemo
useCallback
useContext

react hooks

---

react/16.react_useRef.md
react/17.react_useReducer.md
react/18.react_custom_hook.md

added react custom hooks article

react custom hooks

---

react/00.React_Components_States/package-lock.json
react/00.React_Components_States/package.json
react/00.React_Components_States/src/Test.js
react/00.React_Components_States/src/components/Classbased.js
react/00.React_Components_States/src/components/Functional.js
react/00.React_Components_States/src/index.js
react/19.react_react_router_dom.md

react-router-dom

---

react/assignment/01.30dec.md

As i experience that in state topic 2nd question is repeted so in case of that Q i have added 8th question that is more imp to know and i feel that question is imp so replace 2nd question from 8th question

Krutagya kaneria want to change one question from the topic state

---

mongodb/node_crud/.gitignore
mongodb/node_crud/00.crud_app.js
mongodb/node_crud/01.async_app.js
mongodb/node_crud/02.express_crud.js
mongodb/node_crud/package-lock.json
mongodb/node_crud/package.json

crud mongodb

---

mongodb/assignments/01/api.md
mongodb/assignments/02/api.md
mongodb/assignments/03/api.md
mongodb/assignments/04/api.md

update mongodb readme

---

oops_cpp/05.encapsulation_abstraction.md
oops_cpp/06.inheritance_polymorphism.md

cpp oops four core concepts

---

tools.md

added full stack tools useful in react

---

react/22.react_redux.md
react/23.react_redux_toolkit_intro.md
react/24.react_redux_toolkit_query.md
react/25.react_redux_toolkit_api_call.md
react/26.react_redux_toolkit_storage.md

react redux

---

database/05.understanding_sql_databases.md

@PatelNeelMahesh  improve this spelling mistake.

Improve the spelling mistake in the name.

---

OpenIdeas.md

added few group projects

---

backend_with_node.js/16.monolithic_architecture.md
backend_with_node.js/17.building_monolithic_applications.md
backend_with_node.js/18.scaling_monolithic_appplications.md

added monolithic articles

---

backend_with_node.js/19.microservice_architecture.md
backend_with_node.js/20.designing_microservices.md
backend_with_node.js/21.building_microservices_with_nodejs.md
backend_with_node.js/22.case_study.md

microservices

---

angular/01.angular.md
angular/02.overview_setup.md
angular/03.components_templates.md
angular/04.data_binding.md
angular/05.directives_in_angular.md
angular/06.services.md
angular/07.dependency_injection.md
angular/08.routing.md
angular/09.form_in_angular.md

added angular form

---

interview/machine_coding/03.mongodb_coding_round.md

mongodb interview questions

---

interview/online_assesment/cpp.md
interview/online_assesment/mongodb.md
interview/online_assesment/node.md
interview/online_assesment/react.md
interview/online_assesment/stl_questions_for_loom_video.md

stl_questions

---

interview/online_assesment/cpp.md
interview/online_assesment/mongodb.md
interview/online_assesment/node.md
interview/online_assesment/react.md

This pull request addresses the issue of the disorganized C++/STL questions in the provided Markdown file. The original file contained duplicated questions and lacked a clear structure, as shown below:
1. **Removed Duplicates**: 
- Eliminated repeated long-answer and coding questions to ensure a concise list.
2. **Structured Format**:
- Organized questions into two clear sections: "Long-Answer Questions" and "Coding Questions," each with numbered lists for better readability.
3. **Improved Clarity**:
- Ensured consistent formatting and proper Markdown syntax for a professional presentation.
Please include screenshots of the file before the updates for reviewers' reference. Insert the screenshots below:
- **Screenshot **:   
- 
These changes make the `C++_STL_Questions.md` file easier to …

Organize and Restructure C++/STL Questions Markdown File

---

s3_full_stack/08.data_fetching.md

added data fetching methods

---

s3_full_stack/00.assignments/01.md
s3_full_stack/00.assignments/02.md

assignments

---

s3_dsa/04.Hashing and File Structures/01.File Organisation/00.Introduction to File Structure/00.Introduction to File Structure.md
s3_dsa/04.Hashing and File Structures/01.File Organisation/01.Sequential File Organization/Sequential File Organization.md
s3_dsa/04.Hashing and File Structures/01.File Organisation/01.Sequential File Organization/code.md
s3_dsa/04.Hashing and File Structures/01.File Organisation/02. Indexed File Organization/Indexed File Organization.md
s3_dsa/04.Hashing and File Structures/01.File Organisation/02. Indexed File Organization/code.md
s3_dsa/04.Hashing and File Structures/01.File Organisation/03.Relative (or Random) File Organization/Relative (or Random) File Organization.md
s3_dsa/04.Hashing and File Structures/01.File Organisation/03.Relative (or Random) File Organization/code.md
s3_dsa/04.Hashing and File Structures/01.File Organisation/04.Indexing and Hashing in Files/Indexing and Hashing in Files.md
s3_dsa/04.Hashing and File Structures/01.File Organisation/04.Indexing and Hashing in Files/code.md
s3_java/01.Introduction to Java Programming/00.Basic of Java Programming/00.Basic of Java Programming.md
s3_java/01.Introduction to Java Programming/00.Basic of Java Programming/01.JDK, JRE, JVM, JIT.md
s3_java/01.Introduction to Java Programming/01.Data Types/Data Types (Primitive and Wrapper Classes).md
s3_java/01.Introduction to Java Programming/02.String and it's Operations/String and it's operation.md
s3_java/01.Introduction to Java Programming/03.Array and it's Operations/Array and it's operations.md
s3_java/02.Methods, Object, Classses, Conditions & Loops in Java/00.Class, Object & Constructor in Java/00.Class, Object & Constructor in Java.md
s3_java/02.Methods, Object, Classses, Conditions & Loops in Java/00.Class, Object & Constructor in Java/code.md
s3_java/02.Methods, Object, Classses, Conditions & Loops in Java/01.Methods in Java/01.Methods in Java.md
s3_java/02.Methods, Object, Classses, Conditions & Loops in Java/01.Methods in Java/code.md
s3_java/02.Methods, Object, Classses, Conditions & Loops in Java/02.Conditionals and Loops in Java/02.Conditionals and Loops in Java.md
s3_java/02.Methods, Object, Classses, Conditions & Loops in Java/02.Conditionals and Loops in Java/code.md
s3_java/02.Methods, Object, Classses, Conditions & Loops in Java/03.Static and Non-Static in Java/03.Static and Non-Static in Java.md
s3_java/02.Methods, Object, Classses, Conditions & Loops in Java/03.Static and Non-Static in Java/code.md
s3_java/02.Methods, Object, Classses, Conditions & Loops in Java/04.The `this` Keyword in Java/04.The `this` Keyword in Java.md
s3_java/02.Methods, Object, Classses, Conditions & Loops in Java/04.The `this` Keyword in Java/code.md

DSA subject -> Chapters and their internal folders, sub-folders, files are updated.
Java Subject -> Unit- 1,2 Folders, sub-folders, and files are updated.

Update From MySide

---

s3_full_stack/03.testing/test_task.md

added tasks to write test cases

added tasks

---

s3_full_stack/24.mui.md

mui api task
